
workflows:
  ios-workflow:
    name: iOS IPA (no signing)

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/archive/*.xcarchive
